name: nomisal_ui
description: An application to integrate dart ui in nomisal style
version: 0.0.2
repository: https://github.com/nomagicisreal/nomisal_ui

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  lints: ^5.0.0
  test: ^1.24.0
